---
- name: Update repositories
  become: yes
  apt:
    update_cache: yes
    name: git
    state: present
- name: Creates directory
  file: path=/home/salama/fromTravis{{TRAVIS_BUILD_NUMBER}} state=directory
